config/routes.rb
Rails.application.routes.draw do
  resources :cocktails
  resources :ingredients, only: [:new, :add]
  get '/', to: 'cocktails#index'
  delete '/cocktails/:id', to: 'cocktails#destroy', as: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates  :description, presence: true
  validates_uniqueness_of :ingredient_id, scope: [:cocktail_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :destroy]
  def new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.new()
  end

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def edit
  end

  def remove
  end

  def update
  end
  def create
    @cocktails = Cocktail.all
    cocktail_name = params['cocktail']
    cock = Cocktail.new(cocktails_params)
    cock.save
    result = params[:cocktail][:ingredient].split(/[:,$]/)
    results = objectify(result)
    results.each do |ingredient|
      # Dose.create(cocktail_id: cock.id, ingredient: ingredient, description: description)
      ing_id = Ingredient.find_by(name: ingredient[:name])
      description = ingredient[:description]
      Dose.create({cocktail_id: cock.id, ingredient_id: ing_id.id, description: description})
    end
    render :index
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path and return
  end

  private
  def objectify(ingredients)
    counter = 1
    description = []
    name = []
    ingredients.each do |item|
      if counter.even?
        description << item
        counter += 1
        else
        name << item
        counter += 1
      end
    end
    returnarr = []
    description.each_with_index { |des, index| returnarr << {name: name[index], description: des} }
    returnarr
  end

  def cocktails_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
  end

  def add
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destory</h1>
<p>Find me in app/views/cocktails/destory.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Find me at next Version Sorry</h1>

app/views/cocktails/index.html.erb
  <div class="navbar">
    <div class="search">
      <label>Search</label>
      <input type="text" name="index" placeholder="Search cocktail">
    </div>
    <div class="add">
      <a href="<%= new_cocktail_path %>"><button>Your Cocktail</button></a>
    </div>
  </div>
  <div class="banner">
    <div class="container">
      <h1>Your Cocktail <br>Your lifestyle<br>Your book</h1>
      <p>Change your life and learn to make cray cocktails at one of our campuses around the world.</p>
    </div>
  </div>

<div class="container">
  <div class="cardbox">
    <!-- Cards should be place here</!-->
    <div class="cards">
      <% if !@cocktails.nil? %>
      <% @cocktails.each do |cocktail| %>
    <div class="card-product">
      <%= cl_image_tag cocktail.photo.key, height: 150, width: 150, crop: :fill if cocktail.photo.attached? %>
      <div class="card-product-infos">
      <h2><%= cocktail.name %></h2>
      <% @dose_ids = cocktail.dose_ids %>
      <div class="scroll-ingredients">
      <% @dose_ids.each do |ingredient| %>
        <p><%= Dose.find(ingredient).ingredient.name %> - <%= Dose.find(ingredient).description %></p>
      <% end %>
      </div>
      <span class="update">
        <%= link_to "", cocktail_path(cocktail), class: "fa fa-pencil fa-lg text-reset" %>
      </span>
      </div>
    </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>
    <!-- Footer here</!-->
  </div>
  <div class="footerr">
    <span>This is footer</span>
  </div>

app/views/cocktails/new.html.erb
<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>

  <div class="navbar">
    <div class="search">
      <label>Search</label>
      <input type="text" name="index" placeholder="Search cocktail">
    </div>
    <div class="add">
      <a href="<%= cocktails_path %>"><button>Go Home!</button></a>
    </div>
  </div>
  <div class="banner">
    <div class="container">
      <h1>Your Cocktail <br>Your lifestyle<br>Your book</h1>
      <p>Change your life and learn to make cray cocktails at one of our campuses around the world.</p>
    </div>
  </div>
  <div class="addbox">

  <div id="contact"><%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>

    <label>Ingredints:</label>
    <select class="form-control select2-multiple" multiple>
      <div class="results">
        <!-- Load ingredients to selector !-->
        <% @ingredients = Ingredient.all.each do |ingredient| %>
          <option class="dropdown-item ingredient-<%= ingredient.name.delete(' ') %>"><%= ingredient.name %></option>
        <% end %>
        <!-- Dosage and cleaner button (clean form and save data) !-->
        <input type="text" id="dose" style="display: none"></input>
        <button class="btn-success" id="add-more" style="display: none">add ingredient</button>
        <input id="results" type="text" name="cocktail[ingredient]" style="display: none">
    </select>
        <%= f.submit %>
  <% end %>
</select>
      </div>
  </div>
</div>
</div>
  <div class="footerr">
    <!-- Footer here</!-->
    <span>This is footer</span>
  </div>

app/views/cocktails/remove.html.erb
<h1>Cocktails#remove</h1>
<p>Find me in app/views/cocktails/remove.html.erb</p>

app/views/cocktails/show.html.erb
  <div class="navbar">
    <div class="search">
      <label>Search</label>
      <input type="text" name="index" placeholder="Search cocktail">
    </div>
    <div class="add">
      <a href="<%= new_cocktail_path %>"><button>New</button></a>
    </div>
    <div class="add">
      <a href="<%= cocktails_path %>"><button>Cocktails</button></a>
    </div>
  </div>
  <div class="banner">
    <div class="container">
      <h1>Your Cocktail <br>Your lifestyle<br>Your book</h1>
      <p>Change your life and learn to make cray cocktails at one of our campuses around the world.</p>
      <a class="btn btn-flat" href="#">Apply now</a>
    </div>
  </div>
<div class="container">
  <div class="cardbox">
    <!-- Cards should be place here</!-->
    <div class="card-product">
      <%= cl_image_tag @cocktail.photo.key, height: 150, width: 150, crop: :fill if @cocktail.photo.attached? %>
      <div class="card-product-infos">
        <h2><%= @cocktail.name %></h2>
      <% @dose_ids = @cocktail.dose_ids %>
      <div class="scroll-ingredients">
        <% @dose_ids.each do |ingredient| %>
          <p><%= Dose.find(ingredient).ingredient.name %> - <%= Dose.find(ingredient).description %></p>
        <% end %>
      </div>
        <span class="update"><%= link_to "", cocktail_path(@cocktail), class: "fa fa-pencil fa-lg text-reset", id: "edit" %></span>
        <span class="remove"><%= link_to "Remove", destroy_path(@cocktail), method: :delete %></span>
     </div>
    </div>
  </div>
</div>
  <div class="footerr">
    <span>This is footer</span>
  </div>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/ingredients/add.html.erb
<h1>Ingredients#add</h1>
<p>Find me in app/views/ingredients/add.html.erb</p>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/1e48876c4f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>